// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgrxiaxlwhjatzdizwmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFncnhpYXhsd2hqYXR6ZGl6d21vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NzU1NjQsImV4cCI6MjA3MTI1MTU2NH0.tZNbSEY8fZDfMtGBMT_YM7rEnynl-LB6sEANX6U0c3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});